language: node_js
node_js:
  - stable
  - "5.1"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
script: cd ./packages && for D in *; do (cd "$D" && npm install && npm test); done
